dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)

    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        jcenter()
    }
}

rootProject.name = "Adelaide"
include(
        ":app",
        ":core:ui",
        ":core:utils",
        ":core:compose-ui",
)
project(':core:ui').projectDir = new File(rootDir, '/AndroidCoreBase/ui')
project(':core:utils').projectDir = new File(rootDir, '/AndroidCoreBase/utils')
project(':core:compose-ui').projectDir = new File(rootDir, '/compose-ui')
