package com.anadolstudio.compose.ui.theme.color

import androidx.compose.runtime.Stable
import androidx.compose.ui.graphics.Color

@Stable
data class AdelaideThemeColors(
    val isLight: Boolean,
    val active: Color,
    val backgroundPrimary: Color,
    val backgroundSecondary: Color,
    val backgroundTabbar: Color,
    val unselectedTextTabbar: Color,
    val buttonPrimary: Color,
    val buttonPrimaryDisabled: Color,
    val buttonPrimaryPressed: Color,
    val buttonPrimaryRipple: Color,
    val buttonSecondaryText: Color,
    val buttonTertiaryText: Color,
    val divider: Color,
    val error: Color,
    val success: Color,
    val errorPressed: Color,
    val progressBar: Color,
    val shimmerElement: Color,
    val shimmerGradient: GradientColor,
    val statusBronze: GradientColor,
    val statusGold: GradientColor,
    val statusPlatinum: GradientColor,
    val statusSilver: GradientColor,
    val textPrimary: Color,
    val inverseTextPrimary: Color,
    val textPrimaryDisabled: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val textQuaternary: Color,
    val calendarBackground: Color,
    val indicatorSelected: Color,
    val indicatorDefault: Color,
    val switchThumbColor: Color,
    val switchCheckedTrackColor: Color,
    val switchUncheckedTrackColor: Color,
    val asteriskColor: Color,
    val bitmapBackgroundColor: Color,
    val handleSheetColor: Color,
    val activeFilterColor: Color,
    val plasticCard: Color,
    val virtualCard: Color,
    val inactiveCard: Color,
    val backgroundTertiary: Color,
    val hintColor: Color,
    val backgroundIndicator: Color,
    val ai80: Color,
    val ai92ecto: Color,
    val ai92euro: Color,
    val fuel92: Color,
    val fuelLess92: Color,
    val ai93: Color,
    val fuel93: Color,
    val fuel95: Color,
    val fuel95plus: Color,
    val ektoDiesel: Color,
    val ai95ecto: Color,
    val ai95euro: Color,
    val fuel98: Color,
    val ai98Ecto: Color,
    val ai98Euro: Color,
    val ai100Ecto: Color,
    val ai100Euro: Color,
    val diesel: Color,
    val dieselEcto: Color,
    val dieselEuro: Color,
    val dieselBio: Color,
    val dieselEco: Color,
    val fuelDieselPlus: Color,
    val fuelDiesel: Color,
    val gas: Color,
    val fuelGas: Color,
    val kerosene: Color,
    val oil: Color,
    val fuelOtherPlus: Color,
    val profileHeader: Color,
    val profileHeaderText: Color,
    val profileRoleBackground: Color,
    val grayUltralight: Color,
    val chipColor: Color,
    val selectedChipColor: Color,
    val iconChipColor: Color,
)

data class GradientColor(
    val colorStart: Color,
    val colorCenter: Color,
    val colorEnd: Color,
)
